### PR TITLE
Fixed offset when dragging in scroll container

### LINKED ISSUE #29: Issue when dragging inside of a container with overflow auto.
Hey,

I am using your component inside a modal window that has a vertical scrollbar. When I drag an item that is out of view the offset of the item is wrong.

### PR DESCRIPTION
**Pull request by manuelbeier**
resolve #29

### CODE REVIEW

**Comment by manuelbeier** [comment]
resolve #29

**Comment by ButlerBorst** [comment]
@primetwig can this get pushed up the chain? I'm also having an issue within a scrollable container and would love a fix.

**Comment by sidbentifraouine** [comment]
Hi, is it possible to merge this PR, the fix works like a charm for me (installed it from the fork) 🙏

**Comment by adelhamad** [comment]
it will be great to merge this pr

**Comment by GimpMaster** [comment]
I updated this merge request to the latest code so there are no more merge conflicts. See this pull request. https://github.com/primetwig/react-nestable/pull/88

**Pull request closed without merging**
